baseURL = "https://github.com/gao114882/myblog.git"
languageCode = "en-us"
title = "gaoqs's Blog"
theme = "m10c"

[params]
  author = "gao qiansong"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/gao114882"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_ChrisJHart"
